// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schaakclubuitslag.DAL;

namespace Schaakclubuitslag.Migrations
{
    [DbContext(typeof(SCUSpelerContext))]
    [Migration("20200318223913_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Schaakclubuitslag.Models.PartijModel", b =>
                {
                    b.Property<int>("PartijId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Dag")
                        .HasColumnType("int");

                    b.Property<int>("SCUSpelerId")
                        .HasColumnType("int");

                    b.Property<int?>("SpelerSCUSpelerId")
                        .HasColumnType("int");

                    b.Property<int>("Uitslag")
                        .HasColumnType("int");

                    b.HasKey("PartijId");

                    b.HasIndex("SpelerSCUSpelerId");

                    b.ToTable("Partij");
                });

            modelBuilder.Entity("Schaakclubuitslag.Models.SCUSpelerModel", b =>
                {
                    b.Property<int>("SCUSpelerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SCUSpelerId");

                    b.ToTable("SCUSpeler");
                });

            modelBuilder.Entity("Schaakclubuitslag.Models.PartijModel", b =>
                {
                    b.HasOne("Schaakclubuitslag.Models.SCUSpelerModel", "Speler")
                        .WithMany()
                        .HasForeignKey("SpelerSCUSpelerId");
                });
#pragma warning restore 612, 618
        }
    }
}
